### ISSUE TITLE
支持Teleport

### ISSUE THREAD

**Issue by lloydzhou** [lloydzhou/antv-x6-vue#10]
https://v3.cn.vuejs.org/guide/teleport.html
支持将子节点渲染到组件外部。
所以可以考虑将子节点渲染到vue-shape的foConten元素里面去。

优点：
1. 一方面提升渲染性能不用在每次renderVueComponent的时候createApp再mount。
2. 另一方面，这个vue的组件实际上是在当前用户空间，更新的时候或许可以交给自定义的组件处理。根本不用去操作foContent

**Comment by lloydzhou** [comment]
原始的x6-vue-shape里面的`VueShapeView`会生成太多的App


![image](https://user-images.githubusercontent.com/1826685/166095910-e5a5be31-5d67-42c9-bdb5-3b33ee56262a.png)

**Comment by lloydzhou** [comment]
使用新版本后，这些组件会挂在当前的vue App上

![image](https://user-images.githubusercontent.com/1826685/166149754-e5d678d2-f829-4ee0-b3bc-406143be1224.png)

**Comment by fengxiaodong28** [comment]
> 原始的x6-vue-shape里面的`VueShapeView`会生成太多的App
> 
> ![image](https://user-images.githubusercontent.com/1826685/166095910-e5a5be31-5d67-42c9-bdb5-3b33ee56262a.png)

这用的是哪个插件？

**Comment by lloydzhou** [comment]
@fengxiaodong28 就是vue官方的开发者插件
![image](https://github.com/lloydzhou/antv-x6-vue/assets/1826685/93cc6d94-8a39-4a19-81b9-d2c4890864a6)
