### ISSUE TITLE
vue-shape teleport渲染问题

### ISSUE THREAD

**Issue by happy-mht** [lloydzhou/antv-x6-vue#15]
使用teleport优化节点，但是一旦设置 node 的visible =false, 然后visible还原为true，此时，修改node的属性（比如移动位置，修改大小）不会触发视图刷新，好像是model层的变化不会被view层接收到了，希望这问题早点能解决。

**Comment by lloydzhou** [comment]
https://github.com/antvis/X6/issues/2505 和这个issue重复了

**Comment by lloydzhou** [comment]
我在使用`antv-x6-vue`渲染的时候，并没有复现
1. temp1.setVisible(false)
2. temp1.setSize(300, 300)
3. temp1.setVisible(true)
4. temp1.setSize(200, 200)

直接在控制台连续的调用setVisible和setSize，这个VueShape的节点是能够正常渲染的。

![image](https://user-images.githubusercontent.com/1826685/184611949-a88375da-9186-495e-8b33-ae2d2a6f9a71.png)

@mht1993 你能提供一个能复现的demo吗？比如在线的codesandbox之类的链接。

或者我后面不使用`antv-x6-vue`再重新测试一下

**Comment by lloydzhou** [comment]
修复代码已合并
